/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rft_calculator;

/**
 *
 * @author kovac
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_torles = new javax.swing.JButton();
        btn_het = new javax.swing.JButton();
        btn_negy = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_nyolc = new javax.swing.JButton();
        btn_ot = new javax.swing.JButton();
        btn_egy = new javax.swing.JButton();
        btn_ketto = new javax.swing.JButton();
        btn_nulla = new javax.swing.JButton();
        btn_osszeadas = new javax.swing.JButton();
        btn_kilenc = new javax.swing.JButton();
        btn_hat = new javax.swing.JButton();
        btn_harom = new javax.swing.JButton();
        btn_tizedespont = new javax.swing.JButton();
        btn_egyenlo = new javax.swing.JButton();
        btn_szorzas = new javax.swing.JButton();
        btn_osztas = new javax.swing.JButton();
        btn_kivonas = new javax.swing.JButton();
        btn_szazalekszamitas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        szamitas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btn_torles.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_torles.setText("Del");
        jPanel1.add(btn_torles);
        btn_torles.setBounds(30, 130, 60, 40);

        btn_het.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_het.setText("7");
        btn_het.setToolTipText("");
        jPanel1.add(btn_het);
        btn_het.setBounds(30, 180, 60, 40);

        btn_negy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_negy.setText("4");
        jPanel1.add(btn_negy);
        btn_negy.setBounds(30, 230, 60, 40);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_clear.setText("Clear");
        jPanel1.add(btn_clear);
        btn_clear.setBounds(100, 130, 60, 40);

        btn_nyolc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_nyolc.setText("8");
        jPanel1.add(btn_nyolc);
        btn_nyolc.setBounds(100, 183, 60, 40);

        btn_ot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ot.setText("5");
        jPanel1.add(btn_ot);
        btn_ot.setBounds(100, 233, 60, 40);

        btn_egy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_egy.setText("1");
        jPanel1.add(btn_egy);
        btn_egy.setBounds(30, 280, 60, 40);

        btn_ketto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ketto.setText("2");
        jPanel1.add(btn_ketto);
        btn_ketto.setBounds(100, 280, 60, 40);

        btn_nulla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_nulla.setText("0");
        jPanel1.add(btn_nulla);
        btn_nulla.setBounds(30, 330, 60, 40);

        btn_osszeadas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_osszeadas.setText("+");
        jPanel1.add(btn_osszeadas);
        btn_osszeadas.setBounds(170, 130, 130, 40);

        btn_kilenc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kilenc.setText("9");
        jPanel1.add(btn_kilenc);
        btn_kilenc.setBounds(170, 183, 60, 40);

        btn_hat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_hat.setText("6");
        jPanel1.add(btn_hat);
        btn_hat.setBounds(170, 233, 60, 40);

        btn_harom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_harom.setText("3");
        jPanel1.add(btn_harom);
        btn_harom.setBounds(170, 280, 60, 40);

        btn_tizedespont.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_tizedespont.setText(".");
        jPanel1.add(btn_tizedespont);
        btn_tizedespont.setBounds(100, 330, 60, 40);

        btn_egyenlo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_egyenlo.setText("=");
        jPanel1.add(btn_egyenlo);
        btn_egyenlo.setBounds(170, 330, 60, 40);

        btn_szorzas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_szorzas.setText("*");
        jPanel1.add(btn_szorzas);
        btn_szorzas.setBounds(240, 230, 60, 40);

        btn_osztas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_osztas.setText("/");
        jPanel1.add(btn_osztas);
        btn_osztas.setBounds(240, 280, 60, 40);

        btn_kivonas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kivonas.setText("-");
        jPanel1.add(btn_kivonas);
        btn_kivonas.setBounds(240, 330, 60, 40);

        btn_szazalekszamitas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_szazalekszamitas.setText("%");
        jPanel1.add(btn_szazalekszamitas);
        btn_szazalekszamitas.setBounds(240, 180, 60, 40);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 390);

        value.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(value);
        value.setBounds(30, 20, 270, 60);

        szamitas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(szamitas);
        szamitas.setBounds(34, 84, 260, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_egy;
    private javax.swing.JButton btn_egyenlo;
    private javax.swing.JButton btn_harom;
    private javax.swing.JButton btn_hat;
    private javax.swing.JButton btn_het;
    private javax.swing.JButton btn_ketto;
    private javax.swing.JButton btn_kilenc;
    private javax.swing.JButton btn_kivonas;
    private javax.swing.JButton btn_negy;
    private javax.swing.JButton btn_nulla;
    private javax.swing.JButton btn_nyolc;
    private javax.swing.JButton btn_osszeadas;
    private javax.swing.JButton btn_osztas;
    private javax.swing.JButton btn_ot;
    private javax.swing.JButton btn_szazalekszamitas;
    private javax.swing.JButton btn_szorzas;
    private javax.swing.JButton btn_tizedespont;
    private javax.swing.JButton btn_torles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel szamitas;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
